// One central catalogue: every product has its own name, category, visual and price.
const items = [
  ['Tomato','Fruit Vegetables','🍅',42],['Cherry Tomato','Fruit Vegetables','🍅',65],['Roma Tomato','Fruit Vegetables','🍅',54],['Green Capsicum','Fruit Vegetables','🫑',75],['Red Capsicum','Fruit Vegetables','🫑',95],['Yellow Capsicum','Fruit Vegetables','🫑',95],['Orange Capsicum','Fruit Vegetables','🫑',95],['Cucumber','Fruit Vegetables','🥒',40],['English Cucumber','Fruit Vegetables','🥒',55],['Zucchini','Fruit Vegetables','🥒',62],['Yellow Zucchini','Fruit Vegetables','🥒',68],['Brinjal','Fruit Vegetables','🍆',48],['Long Brinjal','Fruit Vegetables','🍆',55],['Round Brinjal','Fruit Vegetables','🍆',58],['Okra','Fruit Vegetables','🌿',70],['Green Beans','Fruit Vegetables','🫛',65],['French Beans','Fruit Vegetables','🫛',80],['Sweet Corn','Fruit Vegetables','🌽',60],['Baby Corn','Fruit Vegetables','🌽',85],['Green Peas','Fruit Vegetables','🫛',90],
  ['Potato','Root Vegetables','🥔',32],['Baby Potato','Root Vegetables','🥔',48],['Sweet Potato','Root Vegetables','🍠',58],['Red Potato','Root Vegetables','🥔',45],['Onion','Root Vegetables','🧅',38],['Red Onion','Root Vegetables','🧅',46],['White Onion','Root Vegetables','🧅',44],['Shallots','Root Vegetables','🧅',70],['Carrot','Root Vegetables','🥕',55],['Baby Carrot','Root Vegetables','🥕',72],['Beetroot','Root Vegetables','🫜',52],['Radish','Root Vegetables','🥕',38],['Daikon Radish','Root Vegetables','🥕',48],['Turnip','Root Vegetables','🫜',45],['Parsnip','Root Vegetables','🥕',85],['Taro Root','Root Vegetables','🍠',75],['Yam','Root Vegetables','🍠',70],['Ginger','Root Vegetables','🫚',120],['Garlic','Root Vegetables','🧄',135],['Turmeric','Root Vegetables','🫚',105],['Lotus Root','Root Vegetables','🫜',95],
  ['Spinach','Leafy Greens','🥬',28],['Baby Spinach','Leafy Greens','🥬',55],['Kale','Leafy Greens','🥬',80],['Swiss Chard','Leafy Greens','🥬',75],['Lettuce','Leafy Greens','🥬',45],['Romaine Lettuce','Leafy Greens','🥬',65],['Iceberg Lettuce','Leafy Greens','🥬',60],['Cabbage','Leafy Greens','🥬',35],['Red Cabbage','Leafy Greens','🥬',55],['Chinese Cabbage','Leafy Greens','🥬',52],['Cauliflower','Leafy Greens','🥦',55],['Broccoli','Leafy Greens','🥦',90],['Celery','Leafy Greens','🥬',70],['Bok Choy','Leafy Greens','🥬',58],['Mustard Greens','Leafy Greens','🥬',45],['Fenugreek Leaves','Leafy Greens','🌿',35],['Amaranth Leaves','Leafy Greens','🥬',38],['Drumstick Leaves','Leafy Greens','🌿',50],['Watercress','Leafy Greens','🥬',85],['Collard Greens','Leafy Greens','🥬',75],
  ['Coriander','Herbs & Aromatics','🌿',20],['Mint','Herbs & Aromatics','🌱',25],['Basil','Herbs & Aromatics','🌿',45],['Thai Basil','Herbs & Aromatics','🌿',55],['Curry Leaves','Herbs & Aromatics','🌿',30],['Dill','Herbs & Aromatics','🌿',42],['Parsley','Herbs & Aromatics','🌿',50],['Rosemary','Herbs & Aromatics','🌿',65],['Thyme','Herbs & Aromatics','🌿',60],['Oregano','Herbs & Aromatics','🌿',65],['Sage','Herbs & Aromatics','🌿',70],['Lemongrass','Herbs & Aromatics','🌿',48],['Spring Onion','Herbs & Aromatics','🧅',35],['Chives','Herbs & Aromatics','🌿',55],['Fennel Leaves','Herbs & Aromatics','🌿',40],['Bay Leaves','Herbs & Aromatics','🍃',50],['Makrut Lime Leaves','Herbs & Aromatics','🍃',75],['Celery Leaves','Herbs & Aromatics','🌿',38],['Garlic Chives','Herbs & Aromatics','🌿',52],['Sorrel','Herbs & Aromatics','🌿',58],['Microgreens','Herbs & Aromatics','🌱',95],['Arugula','Herbs & Aromatics','🥬',80],
  ['Bottle Gourd','Gourds','🥒',45],['Bitter Gourd','Gourds','🥒',65],['Ridge Gourd','Gourds','🥒',55],['Snake Gourd','Gourds','🥒',60],['Ash Gourd','Gourds','🎃',42],['Pumpkin','Gourds','🎃',38],['Butternut Squash','Gourds','🎃',70],['Acorn Squash','Gourds','🎃',75],['Chayote','Gourds','🥒',58],['Ivy Gourd','Gourds','🥒',65],['Pointed Gourd','Gourds','🥒',68],['Sponge Gourd','Gourds','🥒',55],['Winter Melon','Gourds','🍈',48],['Yellow Squash','Gourds','🎃',65],['Kabocha Squash','Gourds','🎃',85],['Pattypan Squash','Gourds','🎃',78],['Crookneck Squash','Gourds','🎃',75],
  ['Mushroom','Specialty','🍄',140],['Button Mushroom','Specialty','🍄',130],['Oyster Mushroom','Specialty','🍄',180],['Shiitake Mushroom','Specialty','🍄',260],['Portobello Mushroom','Specialty','🍄',220],['Enoki Mushroom','Specialty','🍄',175],['Asparagus','Specialty','🌿',240],['Artichoke','Specialty','🌿',180],['Brussels Sprouts','Specialty','🥬',180],['Leek','Specialty','🧅',90],['Fennel Bulb','Specialty','🌿',95],['Snap Peas','Specialty','🫛',130],['Snow Peas','Specialty','🫛',145],['Edamame','Specialty','🫛',160],['Bamboo Shoots','Specialty','🎋',130],['Banana Flower','Specialty','🌸',80],['Plantain Flower','Specialty','🌸',85],['Nopales','Specialty','🌵',160],['Romanesco','Specialty','🥦',130],['Kohlrabi','Specialty','🫜',85],['Jicama','Specialty','🫜',95]
];

export const seedProducts = () => items.map(([name,category,image,price], index) => ({
  id:index + 1, name, category, image, price, stock:(index * 11) % 49,
  unit:category === 'Herbs & Aromatics' ? 'bunch' : 'kg', featured:index < 8,
  description:`Freshly sourced ${name.toLowerCase()}, delivered with care.`
}));
