import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const fallbackImage = '/products/eugene-golovesov-M7Mb3hRvoh0-unsplash.jpg';
const ProductImage = ({ src, alt, ...props }) => <img src={src || fallbackImage} alt={alt} onError={event => { event.currentTarget.onerror = null; event.currentTarget.src = fallbackImage; }} {...props} />;
const api = async (path, opts = {}) => { const response = await fetch(`/api${path}`, { headers: { 'Content-Type': 'application/json', ...(localStorage.token ? { Authorization: `Bearer ${localStorage.token}` } : {}) }, ...opts }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).message || 'Please try again.'); return response.status === 204 ? null : response.json(); };
const money = value => `₹${Number(value).toFixed(0)}`;

function App() {
  const [products, setProducts] = useState([]), [category, setCategory] = useState(''), [query, setQuery] = useState(''), [cart, setCart] = useState([]), [page, setPage] = useState('shop'), [selected, setSelected] = useState(null), [toast, setToast] = useState('');
  const load = () => api(`/products?q=${encodeURIComponent(query)}&category=${encodeURIComponent(category)}`).then(setProducts).catch(() => setProducts([]));
  useEffect(load, [query, category]);
  const add = product => { if (!product.stock) return; setCart(items => { const old = items.find(item => item.id === product.id); return old ? items.map(item => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { ...product, quantity: 1 }]; }); setToast(`${product.name} added to basket`); setTimeout(() => setToast(''), 1800); };
  const count = cart.reduce((sum, item) => sum + item.quantity, 0);
  return <><header><button className="brand" onClick={() => setPage('shop')}><span>श्री राम</span><small>Vegetables</small></button><nav><button onClick={() => setPage('shop')}>Shop</button><button onClick={() => document.getElementById('market')?.scrollIntoView({ behavior: 'smooth' })}>Vegetables</button><button onClick={() => setPage('admin')}>Admin</button><button className="basket" onClick={() => setPage('cart')}>Basket <b>{count}</b></button></nav></header>{toast && <div className="toast">✓ {toast}</div>}{page === 'shop' && <Shop {...{ products, category, setCategory, query, setQuery, add, setSelected }} />}{page === 'cart' && <Cart {...{ cart, setCart, setPage, load }} />}{page === 'admin' && <Admin loadStore={load} />}{selected && <Details product={selected} close={() => setSelected(null)} add={add} />}</>;
}

function Shop({ products, category, setCategory, query, setQuery, add, setSelected }) {
  const categories = [...new Set(products.map(product => product.category))];
  return <main><section className="hero"><div><p>FRESH FROM THE FARM</p><h1>सब्ज़ी जो<br /><i>घर जैसा लगे।</i></h1><h2>Shree Ram Vegetables</h2><span>Honest vegetables, carefully selected and delivered fresh to your kitchen.</span><button className="primary" onClick={() => document.getElementById('market').scrollIntoView({ behavior: 'smooth' })}>Shop fresh vegetables →</button></div><ProductImage src="/products/tomato.jpg" alt="Fresh vegetables" /></section><section id="market" className="market"><div className="heading"><div><p>OUR VEGETABLE MARKET</p><h2>Choose today’s freshness</h2></div><input placeholder="Search vegetables" value={query} onChange={event => setQuery(event.target.value)} /></div><div className="chips"><button className={!category ? 'active' : ''} onClick={() => setCategory('')}>All vegetables</button>{categories.map(item => <button className={category === item ? 'active' : ''} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div><div className="grid">{products.map(product => <article className="card" key={product.id}><button className="product-image" onClick={() => setSelected(product)}><ProductImage src={product.imageUrl} alt={product.name} /></button><div className="card-body"><small>{product.category}</small><h3>{product.hindiName} <span>· {product.name}</span></h3><p>{product.description}</p><div><strong>{money(product.price)} <small>/ {product.unit}</small></strong><button className="buy" disabled={!product.stock} onClick={() => add(product)}>{product.stock ? 'Buy' : 'Sold out'}</button></div><button className="details" onClick={() => setSelected(product)}>View vegetable info →</button></div></article>)}</div>{!products.length && <p className="empty">No vegetables found.</p>}</section></main>;
}
function Details({ product, close, add }) { return <div className="modal-backdrop" onClick={close}><article className="detail" onClick={event => event.stopPropagation()}><button className="close" onClick={close}>×</button><ProductImage src={product.imageUrl} alt={product.name} /><div><p>{product.category}</p><h2>{product.hindiName}</h2><h3>{product.name}</h3><span>{product.description}</span><ul><li>Hand-selected for freshness</li><li>Available today: {product.stock} {product.unit}</li><li>Best kept cool and dry</li></ul><strong>{money(product.price)} <small>/ {product.unit}</small></strong><button className="primary" onClick={() => { add(product); close(); }}>Add to basket</button></div></article></div>; }
function Cart({ cart, setCart, setPage, load }) {
  const [form, setForm] = useState({ name: '', phone: '', address: '' }), [done, setDone] = useState(''), [placing, setPlacing] = useState(false); const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const place = async event => { event.preventDefault(); if (placing) return; setPlacing(true); try { const order = await api('/orders', { method: 'POST', body: JSON.stringify({ customer: form, items: cart }) }); setDone(`Order ${order.id} confirmed. We will call you shortly.`); setCart([]); load(); } catch (error) { alert(error.message); } finally { setPlacing(false); } };
  if (done) return <main className="simple"><h1>धन्यवाद!</h1><p>{done}</p><button className="primary" onClick={() => setPage('shop')}>Continue shopping</button></main>;
  return <main className="cart"><h1>Your basket</h1>{!cart.length ? <div className="empty">Your basket is waiting for fresh vegetables.<br /><button className="primary" onClick={() => setPage('shop')}>Shop vegetables</button></div> : <div className="checkout"><section>{cart.map(item => <div className="line" key={item.id}><ProductImage src={item.imageUrl} alt={item.name} /><span><b>{item.hindiName} · {item.name}</b><small>{money(item.price)} / {item.unit}</small></span><div className="counter"><button onClick={() => setCart(all => all.map(product => product.id === item.id ? { ...product, quantity: product.quantity - 1 } : product).filter(product => product.quantity))}>−</button>{item.quantity}<button onClick={() => setCart(all => all.map(product => product.id === item.id ? { ...product, quantity: product.quantity + 1 } : product))}>+</button></div></div>)}</section><form onSubmit={place}><h2>Delivery details</h2>{['name', 'phone', 'address'].map(key => <input required key={key} placeholder={key === 'address' ? 'Delivery address' : key[0].toUpperCase() + key.slice(1)} value={form[key]} onChange={event => setForm({ ...form, [key]: event.target.value })} />)}<h2>Total: {money(total)}</h2><button className="primary" disabled={placing}>{placing ? 'Placing order…' : 'Place order →'}</button></form></div>}</main>;
}

const blankProduct = { hindiName: '', name: '', category: 'Fruit vegetables', price: '', stock: '', unit: 'kg', imageUrl: fallbackImage, description: '' };
function ProductForm({ product, onCancel, onSaved }) {
  const [form, setForm] = useState(product || blankProduct), [saving, setSaving] = useState(false), [error, setError] = useState('');
  const field = (key, label, type = 'text') => <label>{label}<input required={['name', 'hindiName', 'imageUrl'].includes(key)} type={type} value={form[key] ?? ''} onChange={event => setForm({ ...form, [key]: event.target.value })} /></label>;
  const save = async event => { event.preventDefault(); setSaving(true); setError(''); try { await api(product?.id ? `/products/${product.id}` : '/products', { method: product?.id ? 'PUT' : 'POST', body: JSON.stringify(form) }); onSaved(); } catch (reason) { setError(reason.message); } finally { setSaving(false); } };
  return <form className="product-form" onSubmit={save}><h2>{product?.id ? `Edit ${product.name}` : 'Add a product'}</h2><div className="form-grid">{field('name', 'Product name')}{field('hindiName', 'Hindi name')}{field('category', 'Category')}{field('price', 'Price (₹)', 'number')}{field('stock', 'Stock', 'number')}{field('unit', 'Unit')}{field('imageUrl', 'Image URL or local path')}</div><label>Description<textarea value={form.description ?? ''} onChange={event => setForm({ ...form, description: event.target.value })} /></label><div className="form-actions"><button className="buy" disabled={saving}>{saving ? 'Saving…' : 'Save product'}</button>{onCancel && <button type="button" className="details" onClick={onCancel}>Cancel</button>}</div>{error && <p className="error">{error}</p>}</form>;
}
function Admin({ loadStore }) {
  const [token, setToken] = useState(!!localStorage.token), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [products, setProducts] = useState([]), [orders, setOrders] = useState([]), [error, setError] = useState(''), [editing, setEditing] = useState(null), [adding, setAdding] = useState(false);
  const refresh = () => Promise.all([api('/products'), api('/orders')]).then(([catalogue, orderList]) => { setProducts(catalogue); setOrders(orderList); setError(''); }).catch(reason => setError(reason.message)); useEffect(() => { if (token) refresh(); }, [token]);
  const saved = () => { setEditing(null); setAdding(false); refresh(); loadStore(); }; const login = async event => { event.preventDefault(); try { const data = await api('/admin/login', { method: 'POST', body: JSON.stringify({ email, password }) }); localStorage.token = data.token; setToken(true); } catch (reason) { setError(reason.message); } }; const remove = async product => { if (!window.confirm(`Remove ${product.name} from the store?`)) return; try { await api(`/products/${product.id}`, { method: 'DELETE' }); saved(); } catch (reason) { setError(reason.message); } };
  if (!token) return <main className="simple"><p>ADMIN ACCESS</p><h1>Manage Shri Ram Vegetables</h1><form onSubmit={login}><input required placeholder="Email" onChange={event => setEmail(event.target.value)} /><input required type="password" placeholder="Password" onChange={event => setPassword(event.target.value)} /><button className="primary">Sign in</button></form>{error && <p className="error">{error}</p>}</main>;
  return <main className="admin"><div className="heading"><div><p>ADMIN PANEL</p><h1>Store control</h1></div><button className="buy" onClick={() => { setAdding(true); setEditing(null); }}>+ Add product</button></div>{error && <p className="error">{error}</p>}<section className="stats"><div><b>{products.length}</b><span>Vegetables</span></div><div><b>{orders.length}</b><span>Total orders</span></div><div><b>{orders.filter(order => !order.adminRead).length}</b><span>New orders</span></div></section>{(adding || editing) && <ProductForm product={editing} onCancel={() => { setAdding(false); setEditing(null); }} onSaved={saved} />}<section><h2>Catalogue <small>Edit names, photos, pricing or stock. Remove unwanted products.</small></h2><div className="catalogue-admin">{products.map(product => <article key={product.id}><ProductImage src={product.imageUrl} alt="" /><div><b>{product.name}</b><span>{product.hindiName} · {money(product.price)} / {product.unit}</span></div><button className="details" onClick={() => { setEditing(product); setAdding(false); }}>Edit</button><button className="danger" onClick={() => remove(product)}>Remove</button></article>)}</div></section><section><h2>New orders</h2>{!orders.length ? <p className="empty">No orders yet.</p> : orders.map(order => <article className="order" key={order.id}><div><b>{order.id} · {order.customer.name}</b><p>{order.customer.phone} · {order.customer.address}</p><small>{order.items.map(item => `${item.name} × ${item.quantity}`).join(', ')} · {money(order.total)}</small></div>{!order.adminRead && <button className="buy" onClick={() => api(`/orders/${order.id}/read`, { method: 'PATCH' }).then(refresh)}>Mark read</button>}</article>)}</section><button className="details" onClick={() => { localStorage.removeItem('token'); setToken(false); }}>Sign out</button></main>;
}
createRoot(document.getElementById('root')).render(<App />);
